# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: quonfig 0.0.2 ruby lib

Gem::Specification.new do |s|
  s.name = "quonfig".freeze
  s.version = File.read(File.expand_path("VERSION", __dir__)).strip

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Jeff Dwyer".freeze]
  s.date = "2026-04-22"
  s.description = "Quonfig \u2014 feature flags and live config, stored as files in git.".freeze
  s.email = "jeff@quonfig.com".freeze
  s.extra_rdoc_files = [
    "CHANGELOG.md",
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".claude/rules/constitution.md",
    ".claude/rules/git-safety.md",
    ".claude/rules/issue-tracking.md",
    ".claude/rules/testing-workflow.md",
    ".envrc.sample",
    ".github/CODEOWNERS",
    ".github/pull_request_template.md",
    ".github/workflows/release.yml",
    ".github/workflows/ruby.yml",
    ".github/workflows/test.yaml",
    ".rubocop.yml",
    ".tool-versions",
    "CHANGELOG.md",
    "CLAUDE.md",
    "CODEOWNERS",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "dev/allocation_stats",
    "dev/benchmark",
    "dev/console",
    "dev/script_setup.rb",
    "lib/quonfig.rb",
    "lib/quonfig/bound_client.rb",
    "lib/quonfig/caching_http_connection.rb",
    "lib/quonfig/client.rb",
    "lib/quonfig/config_envelope.rb",
    "lib/quonfig/config_loader.rb",
    "lib/quonfig/config_store.rb",
    "lib/quonfig/context.rb",
    "lib/quonfig/datadir.rb",
    "lib/quonfig/duration.rb",
    "lib/quonfig/encryption.rb",
    "lib/quonfig/error.rb",
    "lib/quonfig/errors/env_var_parse_error.rb",
    "lib/quonfig/errors/initialization_timeout_error.rb",
    "lib/quonfig/errors/invalid_sdk_key_error.rb",
    "lib/quonfig/errors/missing_default_error.rb",
    "lib/quonfig/errors/missing_env_var_error.rb",
    "lib/quonfig/errors/type_mismatch_error.rb",
    "lib/quonfig/errors/uninitialized_error.rb",
    "lib/quonfig/evaluation.rb",
    "lib/quonfig/evaluator.rb",
    "lib/quonfig/exponential_backoff.rb",
    "lib/quonfig/fixed_size_hash.rb",
    "lib/quonfig/http_connection.rb",
    "lib/quonfig/internal_logger.rb",
    "lib/quonfig/murmer3.rb",
    "lib/quonfig/options.rb",
    "lib/quonfig/periodic_sync.rb",
    "lib/quonfig/quonfig.rb",
    "lib/quonfig/rate_limit_cache.rb",
    "lib/quonfig/reason.rb",
    "lib/quonfig/resolver.rb",
    "lib/quonfig/semantic_logger_filter.rb",
    "lib/quonfig/semver.rb",
    "lib/quonfig/sse_config_client.rb",
    "lib/quonfig/time_helpers.rb",
    "lib/quonfig/types.rb",
    "lib/quonfig/weighted_value_resolver.rb",
    "quonfig.gemspec",
    "scripts/generate_integration_tests.rb",
    "test/fixtures/datafile.json",
    "test/integration/test_context_precedence.rb",
    "test/integration/test_datadir_environment.rb",
    "test/integration/test_enabled.rb",
    "test/integration/test_enabled_with_contexts.rb",
    "test/integration/test_get.rb",
    "test/integration/test_get_feature_flag.rb",
    "test/integration/test_get_or_raise.rb",
    "test/integration/test_get_weighted_values.rb",
    "test/integration/test_helpers.rb",
    "test/integration/test_helpers_test.rb",
    "test/integration/test_post.rb",
    "test/integration/test_telemetry.rb",
    "test/support/common_helpers.rb",
    "test/support/mock_base_client.rb",
    "test/support/mock_config_loader.rb",
    "test/test_bound_client.rb",
    "test/test_caching_http_connection.rb",
    "test/test_client.rb",
    "test/test_config_loader.rb",
    "test/test_context.rb",
    "test/test_datadir.rb",
    "test/test_duration.rb",
    "test/test_encryption.rb",
    "test/test_evaluator.rb",
    "test/test_exponential_backoff.rb",
    "test/test_fixed_size_hash.rb",
    "test/test_helper.rb",
    "test/test_http_connection.rb",
    "test/test_internal_logger.rb",
    "test/test_options.rb",
    "test/test_rate_limit_cache.rb",
    "test/test_reason.rb",
    "test/test_rename.rb",
    "test/test_resolver.rb",
    "test/test_semantic_logger_filter.rb",
    "test/test_semver.rb",
    "test/test_sse_config_client.rb",
    "test/test_typed_getters.rb",
    "test/test_types.rb",
    "test/test_weighted_value_resolver.rb"
  ]
  s.homepage = "https://github.com/quonfig/sdk-ruby".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "3.5.22".freeze
  s.summary = "Quonfig Ruby SDK".freeze

  s.specification_version = 4

  s.add_runtime_dependency(%q<concurrent-ruby>.freeze, ["~> 1.0".freeze, ">= 1.0.5".freeze])
  s.add_runtime_dependency(%q<faraday>.freeze, [">= 0".freeze])
  s.add_runtime_dependency(%q<ld-eventsource>.freeze, [">= 0".freeze])
  s.add_runtime_dependency(%q<uuid>.freeze, [">= 0".freeze])
  s.add_runtime_dependency(%q<activesupport>.freeze, [">= 4".freeze])
  s.add_development_dependency(%q<allocation_stats>.freeze, [">= 0".freeze])
  s.add_development_dependency(%q<benchmark-ips>.freeze, [">= 0".freeze])
  s.add_development_dependency(%q<bundler>.freeze, [">= 0".freeze])
  s.add_development_dependency(%q<juwelier>.freeze, ["~> 2.4.9".freeze])
  s.add_development_dependency(%q<rdoc>.freeze, [">= 0".freeze])
  s.add_development_dependency(%q<simplecov>.freeze, [">= 0".freeze])
end

