# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: quonfig 1.12.1 ruby lib

Gem::Specification.new do |s|
  s.name = "quonfig".freeze
  s.version = File.read(File.expand_path("VERSION", __dir__)).strip

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Jeff Dwyer".freeze]
  s.date = "2026-04-19"
  s.description = "Quonfig — feature flags and live config, stored as files in git.".freeze
  s.email = "jeff@quonfig.com".freeze
  s.extra_rdoc_files = [
    "CHANGELOG.md",
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "CHANGELOG.md",
    "CODEOWNERS",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/quonfig.rb",
    "lib/quonfig/caching_http_connection.rb",
    "lib/quonfig/client.rb",
    "lib/quonfig/config_client.rb",
    "lib/quonfig/config_client_presenter.rb",
    "lib/quonfig/config_loader.rb",
    "lib/quonfig/config_resolver.rb",
    "lib/quonfig/config_store.rb",
    "lib/quonfig/config_value_unwrapper.rb",
    "lib/quonfig/config_value_wrapper.rb",
    "lib/quonfig/context.rb",
    "lib/quonfig/context_shape.rb",
    "lib/quonfig/context_shape_aggregator.rb",
    "lib/quonfig/criteria_evaluator.rb",
    "lib/quonfig/duration.rb",
    "lib/quonfig/encryption.rb",
    "lib/quonfig/error.rb",
    "lib/quonfig/errors/env_var_parse_error.rb",
    "lib/quonfig/errors/initialization_timeout_error.rb",
    "lib/quonfig/errors/invalid_sdk_key_error.rb",
    "lib/quonfig/errors/missing_default_error.rb",
    "lib/quonfig/errors/missing_env_var_error.rb",
    "lib/quonfig/errors/uninitialized_error.rb",
    "lib/quonfig/evaluation.rb",
    "lib/quonfig/evaluation_summary_aggregator.rb",
    "lib/quonfig/evaluator.rb",
    "lib/quonfig/example_contexts_aggregator.rb",
    "lib/quonfig/exponential_backoff.rb",
    "lib/quonfig/feature_flag_client.rb",
    "lib/quonfig/fixed_size_hash.rb",
    "lib/quonfig/http_connection.rb",
    "lib/quonfig/internal_logger.rb",
    "lib/quonfig/javascript_stub.rb",
    "lib/quonfig/local_config_parser.rb",
    "lib/quonfig/log_level.rb",
    "lib/quonfig/murmer3.rb",
    "lib/quonfig/options.rb",
    "lib/quonfig/periodic_sync.rb",
    "lib/quonfig/quonfig.rb",
    "lib/quonfig/rate_limit_cache.rb",
    "lib/quonfig/resolved_config_presenter.rb",
    "lib/quonfig/resolver.rb",
    "lib/quonfig/semantic_logger_filter.rb",
    "lib/quonfig/semver.rb",
    "lib/quonfig/sse_config_client.rb",
    "lib/quonfig/time_helpers.rb",
    "lib/quonfig/weighted_value_resolver.rb",
    "lib/quonfig/yaml_config_parser.rb",
    "quonfig.gemspec",
    "test/fixtures/datafile.json",
    "test/integration_test.rb",
    "test/integration_test_helpers.rb",
    "test/support/common_helpers.rb",
    "test/support/mock_base_client.rb",
    "test/support/mock_config_client.rb",
    "test/support/mock_config_loader.rb",
    "test/test_caching_http_connection.rb",
    "test/test_client.rb",
    "test/test_config_client.rb",
    "test/test_config_loader.rb",
    "test/test_config_resolver.rb",
    "test/test_config_value_unwrapper.rb",
    "test/test_config_value_wrapper.rb",
    "test/test_context.rb",
    "test/test_context_shape.rb",
    "test/test_context_shape_aggregator.rb",
    "test/test_criteria_evaluator.rb",
    "test/test_duration.rb",
    "test/test_encryption.rb",
    "test/test_evaluation_summary_aggregator.rb",
    "test/test_example_contexts_aggregator.rb",
    "test/test_exponential_backoff.rb",
    "test/test_feature_flag_client.rb",
    "test/test_fixed_size_hash.rb",
    "test/test_helper.rb",
    "test/test_integration.rb",
    "test/test_internal_logger.rb",
    "test/test_javascript_stub.rb",
    "test/test_local_config_parser.rb",
    "test/test_logger_initialization.rb",
    "test/test_options.rb",
    "test/test_prefab.rb",
    "test/test_rate_limit_cache.rb",
    "test/test_resolver.rb",
    "test/test_rename.rb",
    "test/test_semantic_logger_filter.rb",
    "test/test_semver.rb",
    "test/test_sse_config_client.rb",
    "test/test_weighted_value_resolver.rb"
  ]
  s.homepage = "https://github.com/quonfig/sdk-ruby".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "3.4.19".freeze
  s.summary = "Quonfig Ruby SDK".freeze

  s.specification_version = 4

  s.add_runtime_dependency(%q<concurrent-ruby>.freeze, ["~> 1.0", ">= 1.0.5"])
  s.add_runtime_dependency(%q<faraday>.freeze, [">= 0"])
  s.add_runtime_dependency(%q<ld-eventsource>.freeze, [">= 0"])
  s.add_runtime_dependency(%q<uuid>.freeze, [">= 0"])
  s.add_runtime_dependency(%q<activesupport>.freeze, [">= 4"])
  s.add_development_dependency(%q<allocation_stats>.freeze, [">= 0"])
  s.add_development_dependency(%q<benchmark-ips>.freeze, [">= 0"])
  s.add_development_dependency(%q<bundler>.freeze, [">= 0"])
  s.add_development_dependency(%q<juwelier>.freeze, ["~> 2.4.9"])
  s.add_development_dependency(%q<rdoc>.freeze, [">= 0"])
  s.add_development_dependency(%q<simplecov>.freeze, [">= 0"])
end
